### ISSUE TITLE
Bug: ansys-tools-filetransfer version 0.1.0 is not available when using the Ansys Private Pypi as main index. 

### ISSUE THREAD

**Issue by anscfrisson** [ansys/ansys-tools-filetransfer#106]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

From:
https://dev.docs.pyansys.com/how-to/releasing.html#artifact-download

> Warning
> 
> Take care to always use the --index-url switch rather than the --extra-index-url switch. As noted in [pip Documentation](https://pip.pypa.io/en/stable/cli/pip_install/), the --index-url switch changes the Python Package Index, which forces pip to use only packages from that package index.
> 
> The Ansys package index uses PyPI upstream. This prevents other users from being able to inject packages from PyPI that would supersede Ansys packages, even if they are of a higher version.
> 
> This is not the case if you use --extra-index-url, which adds to rather than replaces the default package index. For security, do not use --extra-index-url.

If I define environment variables in github actions:
* `PIP_EXTRA_INDEX_URL: "https://${{ secrets.PYANSYS_PRIVATE_PYPI_PAT }}@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple"`: `ansys-api-tools-filetransfer` can be retrieved
* `PIP_INDEX_URL: "https://${{ secrets.PYANSYS_PRIVATE_PYPI_PAT }}@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple"`: fails with:
    ```
    ERROR: Could not find a version that satisfies the requirement ansys-api-tools-filetransfer<0.2.0,>=0.1.0 (from ansys-tools-filetransfer) (from versions: 0.1.dev0, 0.1.dev1, 0.1.dev2, 0.1.dev3, 0.1.dev4, 0.1.dev5)
    ERROR: No matching distribution found for ansys-api-tools-filetransfer<0.2.0,>=0.1.0
    ```
(`***` internal project)

Are ansys-api-tools-filetransfer versions > 0.1.dev5 not relayed by the Ansys Private Pypi?

### 📝 Steps to reproduce

Request the value of the `PYANSYS_PYPI_PRIVATE_READ_PAT` token by sending an email to the [pyansys.core@ansys.com](mailto:pyansys.core%40ansys.com) email.

## Works

```bash
export PIP_INDEX_URL=
export PIP_EXTRA_INDEX_URL="https://$PYANSYS_PYPI_PRIVATE_READ_PAT@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple"
pip install ansys-tools-filetransfer==0.1.0
```

```bash
  Downloading https://pkgs.dev.azure.com/pyansys/_packaging/705e121a-9631-49f5-8aaf-c7142856f923/pypi/download/ansys-tools-filetransfer/0.1/ansys_tools_filetransfer-0.1.0-py3-none-any.whl (9.6 kB)
```

## Fails

```bash
export PIP_INDEX_URL="https://$PYANSYS_PYPI_PRIVATE_READ_PAT@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple"
export PIP_EXTRA_INDEX_URL=
pip install ansys-tools-filetransfer==0.1.0
```

```pip
ERROR: Could not find a version that satisfies the requirement ansys-api-tools-filetransfer<0.2.0,>=0.1.0 (from ansys-tools-filetransfer) (from versions: 0.1.dev0, 0.1.dev1, 0.1.dev2, 0.1.dev3, 0.1.dev4, 0.1.dev5)
ERROR: No matching distribution found for ansys-api-tools-filetransfer<0.2.0,>=0.1.0
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

251 (but does not matter here)

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
(none: tested from new virtual environment)
```

**Comment by anscfrisson** [comment]
We would also appreciate if the solution for the fix could be shared for potential future similar issues.

**Comment by greschd** [comment]
I think the problem here might be `ansys-tools-filetransfer` having been published _explicitly_ to the internal PyPI before its release on the public one.
Since explicit publishing overrides the mirroring (this is one of the security features provided by running an internal PyPI), it is not updated.

I would _guess_ the resolution is an administrative action on the internal PyPI: deleting the explicitly-uploaded package from the internal PyPI, and / or allowing it to mirror public PyPI.

Tagging @RobPasMue @jorgepiloto, who may have the access rights to do this.

**Comment by RobPasMue** [comment]
On it - we will allow for upstream versions from PyPI

**Comment by RobPasMue** [comment]
Done. The solution is allowing for externally sourced versions (i.e. from the public PyPI). This has to be done on a package per package basis. I already presented the solution in the past @anscfrisson in https://github.com/ansys/pyprimemesh/issues/760#issuecomment-2082603972

**Comment by anscfrisson** [comment]
> Done. The solution is allowing for externally sourced versions (i.e. from the public PyPI). This has to be done on a package per package basis. I already presented the solution in the past @anscfrisson in [ansys/pyprimemesh#760 (comment)](https://github.com/ansys/pyprimemesh/issues/760#issuecomment-2082603972)

Thank you @RobPasMue for fixing this!

I had seen your comment, could you please point us to what code you modified?

**Comment by RobPasMue** [comment]
There was no modification done on code. The modification was done at the private PyPI configuration level. 😸

**Comment by greschd** [comment]
@RobPasMue I think we should document this somewhere, and maybe communicate to the PyAnsys community. I had been tangentially aware that the internal PyPI had these options, but didn't fully make the connection that it needed to be done to this library.

**Comment by RobPasMue** [comment]
Sure, I will sign up on the agenda for tomorrow and we will try to come up with a clear statement :)
